### ISSUE TITLE
Hide self view

### ISSUE THREAD

**Issue by blopker** [blopker/totem#154]
Design what the hidden self-view shoudl look like, and how people use it to see themselves when they want.
@sebasnieb

**Comment by sebasnieb** [comment]
Hi @blopker so for this I combine the following:
- the "Next tag" at the top 
- The separator between who is talking and the other people who are listening with you.
- I decided to have everyone with their names on the video, so they know who they are in case nobody has the video on or not a picture.
- Also, I put a provisional idea of how the avatar can look ( check the "you" video frame)
- To identify where am I we might just have, instead of the "me" tag that we removed, a "you" in your name, it is shorter and easier to recognize.
- I saw that the action bar where the buttons are, is too big both in mobile and desktop - let's reduce it, so it is not that prominent from H108  to H84
- In the desktop version since we have this huge bar at the bottom we don't need to have the title at the top, so I was thinking to make use of it and leave the name of the circle at the bottom .


Link of the prototype of the hide self view : so here you will be hovering over your own profile , then you will have the possibility to minimize the screen. then when minimizing you can expand it again.
https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=694%3A11492&node-id=1926%3A27136&viewport=241%2C48%2C0.35&scaling=min-zoom&starting-point-node-id=1915%3A26673

For mobile would be similar, we would tap on our profile and shrink it making it less visible.
https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=694%3A11492&node-id=1890%3A26474&viewport=241%2C48%2C0.35&scaling=min-zoom&starting-point-node-id=1915%3A26673

Let me know your thoughts

**Comment by blopker** [comment]
Dup!
