### ISSUE TITLE
Waiting room video placement

### ISSUE THREAD

**Issue by sebasnieb** [blopker/totem#183]
## Overview
When arriving in the waiting room and the circle itself, currently the video is in place in the center of the screen.
The idea is that the video screens get organized from top left to bottom right, so the order is clearer and the layout doesnt change too much

## Screenshot
<img width="1260" alt="Capture d’écran 2022-06-04 à 8 43 31 PM" src="https://user-images.githubusercontent.com/32967293/172055111-cfb25f5a-bf26-4e97-81c8-f3b2095f88b0.png">

## Description
Fingma file link: [here](https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=2372%3A28420)

**Comment by blopker** [comment]
Thanks for this. The change was something that I was playing with recently to make better use of the screen real estate. Both this view and the list view for participants on the sidebar use the same layout engine (currently). This is Circle User Layout at https://app.heytotem.com/#/dev

With the original design I noticed the waiting room looked empty even with 5+ people in it. I think this is one of these things that we didn't revisit after the change from the audio-only format where the only thing to show was profile images, so it didn't matter much.

I'll revert for now, but I do think we should revisit it because of the issues I mentioned.

**Comment by blopker** [comment]
Fixed. This will change next time we release.
